### ISSUE TITLE
Official Announcement: Release of the revised version according to the OCR-D Level 2 guidelines

### ISSUE THREAD

**Issue by JKamlah** [UB-Mannheim/AustrianNewspapers#39]
Hello everyone,
we plan to publish the revised version according to the OCR-D Level 2 guidelines in this repository in the coming days.
In the past months, the GroundTruth was corrected and upgraded by student assistants and project staff. The long s and the double oblique hyphen were updated consistently and any remaining transcription errors were corrected as far as possible. The polygons of the regions and text lines have been corrected, as well as the reading order. The regions were also tagged. Further information on the optimisations will be available at the time of publication.

The following steps are planned for the publication:

- [x] Tagging of the current status
- [x] The 'master' branch will be renamed to 'main'
- [x]  Replace current files with revised files (OCR-D Level 2) in main branch.  There will be only PAGE XML files and instructions on how to generate lines from PAGE XML files. The structure of the repository will follow the [OCR-D GT Repo template](https://github.com/tboenig/gt-repo-template) and the README will also be adapted accordingly. The source of origin and other references will remain the same.

We hope you will enjoy the revised version.

**Comment by stweil** [comment]
cc @wollmers who contributed most commits to this repository

**Comment by wollmers** [comment]
That's very fine to have a standard.

**Comment by stweil** [comment]
Steps 1 and 2 are now done. Local clones of the repository can be updated using these commands:
```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
git remote prune origin
```

**Comment by JKamlah** [comment]
We are happy to announce that the new revised version is now available. 🥳 
We are currently still expanding the wiki pages and will provide additional information and statistics on the revised dataset.

**Comment by stweil** [comment]
@JKamlah, can we close this issue?

Of course there will be further improvements and transcription fixes (like the ones which I made recently), so more releases can be made in the future.

**Comment by JKamlah** [comment]
All tasks completed!
